local normal = {
	{ "<Escape>", "<vis-mode-normal-escape>", "Return to normal mode" },
	{ ":", "<vis-prompt-show>", "Open command prompt" },

	{ "h", "<vis-motion-char-prev>", "Move left" },
	{ "j", "<vis-motion-line-down>", "Move down" },
	{ "k", "<vis-motion-line-up>", "Move up" },
	{ "l", "<vis-motion-char-next>", "Move right" },
	{ "<Left>", "<vis-motion-char-prev>", "Move left" },
	{ "<Down>", "<vis-motion-line-down>", "Move down" },
	{ "<Up>", "<vis-motion-line-up>", "Move up" },
	{ "<Right>", "<vis-motion-char-next>", "Move right" },
	{ "w", "<vis-motion-word-start-next>", "Select next word start" },
	{ "b", "<vis-motion-word-start-prev>", "Select previous word start" },
	{ "e", "<vis-motion-word-end-next>", "Select next word end" },
	{ "W", "<vis-motion-bigword-start-next>", "Select next WORD start" },
	{ "B", "<vis-motion-bigword-start-prev>", "Select previous WORD start" },
	{ "E", "<vis-motion-bigword-end-next>", "Select next WORD end" },
	{ "f", "<vis-motion-to-right>", "Select to next char" },
	{ "t", "<vis-motion-till-right>", "Select till next char" },
	{ "F", "<vis-motion-to-left>", "Select to previous char" },
	{ "T", "<vis-motion-till-left>", "Select till previous char" },
	{ "gg", "<vis-motion-line-first>", "Go to first line" },
	{ "G", "<vis-motion-line-last>", "Go to last line" },
	{ "ge", "<vis-motion-line-last>", "Go to end of file" },
	{ "gs", "<vis-motion-line-start>", "Go to first non-blank" },
	{ "gl", "<vis-motion-line-end>", "Go to line end" },
	{ "<Home>", "<vis-motion-line-begin>", "Go to line start" },
	{ "<End>", "<vis-motion-line-end>", "Go to line end" },
	{ "<PageUp>", "<vis-window-page-up>", "Page up" },
	{ "<PageDown>", "<vis-window-page-down>", "Page down" },
	{ "<C-b>", "<vis-window-page-up>", "Page up" },
	{ "<C-f>", "<vis-window-page-down>", "Page down" },
	{ "<C-u>", "<vis-window-halfpage-up>", "Half page up" },
	{ "<C-d>", "<vis-window-halfpage-down>", "Half page down" },
	{ "<C-o>", "<vis-jumplist-prev>", "Jump backward" },
	{ "<C-i>", "<vis-jumplist-next>", "Jump forward" },
	{ "<C-s>", "<vis-jumplist-save>", "Save jump position" },
	{ "<C-w>s", "<vis-prompt-show>split<Enter>", "Horizontal split" },
	{ "<C-w>v", "<vis-prompt-show>vsplit<Enter>", "Vertical split" },
	{ "<C-w>h", "<vis-window-prev>", "Focus previous window" },
	{ "<C-w>j", "<vis-window-next>", "Focus next window" },
	{ "<C-w>k", "<vis-window-prev>", "Focus previous window" },
	{ "<C-w>l", "<vis-window-next>", "Focus next window" },
	{ "<C-w><Left>", "<vis-window-prev>", "Focus previous window" },
	{ "<C-w><Down>", "<vis-window-next>", "Focus next window" },
	{ "<C-w><Up>", "<vis-window-prev>", "Focus previous window" },
	{ "<C-w><Right>", "<vis-window-next>", "Focus next window" },
	{ "<C-w>w", "<vis-window-next>", "Focus next window" },
	{ "<C-w><C-w>", "<vis-window-next>", "Focus next window" },
	{ "zt", "<vis-window-redraw-top>", "Scroll cursor line to top" },
	{ "zz", "<vis-window-redraw-center>", "Scroll cursor line to center" },
	{ "zb", "<vis-window-redraw-bottom>", "Scroll cursor line to bottom" },
	{ "<Space>w", "<vis-prompt-show>w<Enter>", "Write file" },
	{ "<Space>q", "<vis-prompt-show>q<Enter>", "Quit window" },
	{ " w", "<vis-prompt-show>w<Enter>", "Write file" },
	{ " q", "<vis-prompt-show>q<Enter>", "Quit window" },

	{ "v", "<vis-helix-select-toggle>", "Select mode" },
	{ "V", "<vis-mode-visual-linewise>", "Line select mode" },
	{ "x", "<vis-helix-line-select>", "Select current line" },
	{ "X", "<vis-helix-line-select-current>", "Select current line" },
	{ "i", "<vis-mode-insert>", "Insert mode" },
	{ "a", "<vis-append-char-next>", "Append mode" },
	{ "I", "<vis-insert-line-start>", "Insert at line start" },
	{ "A", "<vis-append-line-end>", "Insert at line end" },
	{ "o", "<vis-open-line-below>", "Open line below" },
	{ "O", "<vis-open-line-above>", "Open line above" },
	{ "r", "<vis-replace-char>", "Replace char" },
	{ "R", "<vis-mode-replace>", "Replace mode" },
	{ "u", "<vis-undo>", "Undo" },
	{ "U", "<vis-redo>", "Redo" },
	{ "y", "<vis-operator-yank>", "Yank selection" },
	{ "p", "<vis-put-after>", "Paste after" },
	{ "P", "<vis-put-before>", "Paste before" },
	{ "C", "<vis-selection-new-lines-below>", "Copy selection to next line" },
	{ "<M-C>", "<vis-selection-new-lines-above>", "Copy selection to previous line" },
	{ ",", "<vis-selections-remove-all>", "Keep primary selection" },
	{ "<M-,>", "<vis-selections-remove-last>", "Remove primary selection" },
	{ "&", "<vis-selections-align>", "Align selections" },
	{ "d", "<vis-operator-delete>", "Delete selection" },
	{ "c", "<vis-operator-change>", "Change selection" },
	{ ">", "<vis-operator-shift-right>", "Indent" },
	{ "<", "<vis-operator-shift-left>", "Unindent" },
	{ "/", "<vis-search-forward>", "Search forward" },
	{ "?", "<vis-search-backward>", "Search backward" },
	{ "n", "<vis-motion-search-repeat-forward>", "Next search match" },
	{ "N", "<vis-motion-search-repeat-backward>", "Previous search match" },
	{ "*", "<vis-helix-search-word-forward>", "Set search pattern to selection" },
	{ "\"", "<vis-register>", "Select register" },

	{ ";", "<vis-helix-collapse-selection>", "Collapse to cursor" },

	{ "0", "<vis-count-0>", "Count" },
	{ "1", "<vis-count-1>", "Count" },
	{ "2", "<vis-count-2>", "Count" },
	{ "3", "<vis-count-3>", "Count" },
	{ "4", "<vis-count-4>", "Count" },
	{ "5", "<vis-count-5>", "Count" },
	{ "6", "<vis-count-6>", "Count" },
	{ "7", "<vis-count-7>", "Count" },
	{ "8", "<vis-count-8>", "Count" },
	{ "9", "<vis-count-9>", "Count" },
}

local visual = {
	{ "<Escape>", "<vis-mode-normal>", "Return to normal mode" },
	{ "h", "<vis-mode-normal><vis-motion-char-prev>", "Move left" },
	{ "j", "<vis-mode-normal><vis-motion-line-down>", "Move down" },
	{ "k", "<vis-mode-normal><vis-motion-line-up>", "Move up" },
	{ "l", "<vis-mode-normal><vis-motion-char-next>", "Move right" },
	{ "<Left>", "<vis-mode-normal><vis-motion-char-prev>", "Move left" },
	{ "<Down>", "<vis-mode-normal><vis-motion-line-down>", "Move down" },
	{ "<Up>", "<vis-mode-normal><vis-motion-line-up>", "Move up" },
	{ "<Right>", "<vis-mode-normal><vis-motion-char-next>", "Move right" },
	{ "w", "<vis-motion-word-start-next>", "Select next word start" },
	{ "b", "<vis-motion-word-start-prev>", "Select previous word start" },
	{ "e", "<vis-motion-word-end-next>", "Select next word end" },
	{ "W", "<vis-motion-bigword-start-next>", "Select next WORD start" },
	{ "B", "<vis-motion-bigword-start-prev>", "Select previous WORD start" },
	{ "E", "<vis-motion-bigword-end-next>", "Select next WORD end" },
	{ "f", "<vis-motion-to-line-right>", "Select to next char in line" },
	{ "t", "<vis-motion-till-line-right>", "Select till next char in line" },
	{ "F", "<vis-motion-to-line-left>", "Select to previous char in line" },
	{ "T", "<vis-motion-till-line-left>", "Select till previous char in line" },
	{ "gg", "<vis-mode-normal><vis-motion-line-first>", "Go to first line" },
	{ "G", "<vis-mode-normal><vis-motion-line-last>", "Go to last line" },
	{ "ge", "<vis-mode-normal><vis-motion-line-last>", "Go to end of file" },
	{ "gs", "<vis-mode-normal><vis-motion-line-start>", "Go to first non-blank" },
	{ "gl", "<vis-mode-normal><vis-motion-line-end>", "Go to line end" },
	{ "<Home>", "<vis-mode-normal><vis-motion-line-begin>", "Go to line start" },
	{ "<End>", "<vis-mode-normal><vis-motion-line-end>", "Go to line end" },
	{ "n", "<vis-motion-search-repeat-forward>", "Select next search match" },
	{ "N", "<vis-motion-search-repeat-backward>", "Select previous search match" },
	{ "*", "<vis-motion-search-word-forward>", "Select next word match" },
	{ ":", "<vis-prompt-show>", "Open command prompt" },
	{ ">", "<vis-operator-shift-right>", "Indent selection" },
	{ "<", "<vis-operator-shift-left>", "Unindent selection" },
	{ "<Space>w", "<vis-prompt-show>w<Enter>", "Write file" },
	{ "<Space>q", "<vis-prompt-show>q<Enter>", "Quit window" },
	{ " w", "<vis-prompt-show>w<Enter>", "Write file" },
	{ " q", "<vis-prompt-show>q<Enter>", "Quit window" },
	{ "u", "<vis-undo>", "Undo" },
	{ "U", "<vis-redo>", "Redo" },
	{ ";", "<vis-helix-collapse-selection>", "Collapse to cursor" },
	{ "x", "<vis-mode-normal><vis-mode-visual-linewise>", "Switch to line selection" },
	{ "X", "<vis-mode-normal><vis-mode-visual-linewise>", "Switch to line selection" },
	{ "d", "<vis-operator-delete>", "Delete selection" },
	{ "c", "<vis-operator-change>", "Change selection" },
	{ "y", "<vis-operator-yank>", "Yank selection" },
	{ "p", "<vis-put-after>", "Paste after" },
	{ "P", "<vis-put-before>", "Paste before" },
	{ "C", "<vis-selection-new-lines-below>", "Copy selection to next line" },
	{ "<M-C>", "<vis-selection-new-lines-above>", "Copy selection to previous line" },
	{ ",", "<vis-selections-remove-all>", "Keep primary selection" },
	{ "<M-,>", "<vis-selections-remove-last>", "Remove primary selection" },
	{ "&", "<vis-selections-align>", "Align selections" },
}

local visual_line = {
	{ "<Escape>", "<vis-mode-normal>", "Return to normal mode" },
	{ "j", "<vis-motion-line-down>", "Extend selection down" },
	{ "k", "<vis-motion-line-up>", "Extend selection up" },
	{ "<Down>", "<vis-motion-line-down>", "Extend selection down" },
	{ "<Up>", "<vis-motion-line-up>", "Extend selection up" },
	{ "x", "<vis-motion-line-down>", "Extend selection down" },
	{ "X", "<vis-motion-line-up>", "Extend selection up" },
	{ "d", "<vis-operator-delete>", "Delete selection" },
	{ "c", "<vis-operator-change>", "Change selection" },
	{ "y", "<vis-operator-yank>", "Yank selection" },
	{ "p", "<vis-put-after>", "Paste after" },
	{ "P", "<vis-put-before>", "Paste before" },
	{ ":", "<vis-prompt-show>", "Open command prompt" },
	{ ">", "<vis-operator-shift-right>", "Indent selection" },
	{ "<", "<vis-operator-shift-left>", "Unindent selection" },
	{ "<Space>w", "<vis-prompt-show>w<Enter>", "Write file" },
	{ "<Space>q", "<vis-prompt-show>q<Enter>", "Quit window" },
	{ " w", "<vis-prompt-show>w<Enter>", "Write file" },
	{ " q", "<vis-prompt-show>q<Enter>", "Quit window" },
	{ "u", "<vis-undo>", "Undo" },
	{ "U", "<vis-redo>", "Redo" },
	{ "C", "<vis-selection-new-lines-below>", "Copy selection to next line" },
	{ "<M-C>", "<vis-selection-new-lines-above>", "Copy selection to previous line" },
	{ ",", "<vis-selections-remove-all>", "Keep primary selection" },
	{ "<M-,>", "<vis-selections-remove-last>", "Remove primary selection" },
	{ "&", "<vis-selections-align>", "Align selections" },
}

local insert = {
	{ "<Escape>", "<vis-mode-normal>", "Return to normal mode" },
	{ "<C-h>", "<vis-delete-char-prev>", "Delete previous char" },
	{ "<Backspace>", "<vis-delete-char-prev>", "Delete previous char" },
	{ "<Delete>", "<vis-delete-char-next>", "Delete next char" },
	{ "<C-d>", "<vis-delete-char-next>", "Delete next char" },
	{ "<C-w>", "<vis-delete-word-prev>", "Delete previous word" },
	{ "<C-u>", "<vis-delete-line-begin>", "Delete to line start" },
	{ "<C-k>", "<Escape><vis-operator-delete><vis-motion-line-end><vis-mode-insert>", "Delete to line end" },
	{ "<Enter>", "<vis-insert-newline>", "Insert line break" },
	{ "<C-j>", "<vis-insert-newline>", "Insert line break" },
	{ "<Tab>", "<vis-insert-tab>", "Insert tab" },
	{ "<Left>", "<vis-motion-char-prev>", "Move left" },
	{ "<Right>", "<vis-motion-char-next>", "Move right" },
	{ "<Up>", "<vis-motion-line-up>", "Move up" },
	{ "<Down>", "<vis-motion-line-down>", "Move down" },
	{ "<Home>", "<vis-motion-line-start>", "Move to line start" },
	{ "<End>", "<vis-motion-line-end>", "Move to line end" },
	{ "<PageUp>", "<vis-window-page-up>", "Page up" },
	{ "<PageDown>", "<vis-window-page-down>", "Page down" },
}

local function map_all(manager, win, mode, mappings)
	for _, mapping in ipairs(mappings) do
		local key, rhs, help = mapping[1], mapping[2], mapping[3]
		if not manager.bind(win, mode, key, rhs, help) then
			return false
		end
	end
	return true
end

return {
	apply = function(manager, win)
		vis:command("set ignorecase on")
		if not manager.shadow_defaults(win) then
			return false
		end
		return map_all(manager, win, vis.modes.NORMAL, normal) and
		       map_all(manager, win, vis.modes.VISUAL, visual) and
		       map_all(manager, win, vis.modes.VISUAL_LINE, visual_line) and
		       map_all(manager, win, vis.modes.INSERT, insert)
	end,
}
